### ISSUE TITLE
Disable command handlers in DM context

### ISSUE THREAD

**Issue by azuraga** [org-araga/doppler#6]
Command handlers are currently made for guild channels. Therefore, the event it listens to should be `onGuildMessageReceived` instead of `onMessageReceived`.

Currently, if a user prompts a command, the following error is shown because of this malfunction:

```java
Exception in thread "Command Execution: 16417582" java.lang.IllegalStateException: This message event did not happen in a text channel
        at net.dv8tion.jda.api.events.message.GenericMessageEvent.getTextChannel(GenericMessageEvent.java:155)
        at core.commands.execution.DiscordCommandHandler.execute(DiscordCommandHandler.java:94)
        at core.commands.execution.DiscordCommandHandler.handle(DiscordCommandHandler.java:73)
        at core.commands.execution.DiscordCommandHandler.lambda$onMessageReceived$0(DiscordCommandHandler.java:43)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by azuraga** [comment]
Solved in v1.0.0
